replicaCount: 1

resources:
  requests:
    cpu: 10m
    memory: 256Mi
  limits:
    cpu: 1000m
    memory: 1024Mi

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx-ingress-private
  hosts:
    - host: hermes-dev.lco.gtn
      paths:
        - "/"
hermes:
  backendUrl: http://hermes-dev.lco.gtn/
