# Helm chart values for Production Deployment
replicaCount: 3

resources:
  requests:
    cpu: 50m
    memory: 256Mi
  limits:
    cpu: 1000m
    memory: 1024Mi

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx-ingress-public
    nginx.ingress.kubernetes.io/proxy-buffers-number: "16"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "5M"
    nginx.ingress.kubernetes.io/large-client-header-buffers: 16 5M
    nginx.ingress.kubernetes.io/server-snippet: | # this is where the magic happens
      client_header_buffer_size 5M;
      large_client_header_buffers 16 5M;
  hosts:
    - host: hermes.lco.global
      paths:
        - "/"

hermes:
  backendUrl: https://hermes.lco.global/
