replicaCount: 2

resources:
  requests:
    cpu: 10m
    memory: 256Mi
  limits:
    cpu: 1000m
    memory: 1024Mi

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx-ingress-public
  # This is LCO specific nomenclature for lco.gtn vs lco.global.
  # This makes sure the load balancer picks up the dns stuff.
  hosts:
    - host: hermes-dev.lco.global
      paths:
        - "/"
hermes:
  backendUrl: https://hermes-dev.lco.global/
