apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hermes-frontend.fullname" . }}

data:
  env-config.js: |
    _env_ = {VUE_APP_HERMES_BACKEND_ROOT_URL: "{{ .Values.hermes.backendUrl -}}" };
